name: glamify
description: "Glamify - تطبيق التجميل والعناية الشخصية الرائد في المنطقة"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.3.0  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
 
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  shared_preferences: ^2.2.2
  image_picker: ^1.2.0
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0
  crypto: ^3.0.3
  easy_stepper: ^0.8.5+1
  simple_animations: ^5.0.2
  flutter_vector_icons: ^2.0.0
  pinput: ^4.0.0
  dropdown_button2: ^2.3.9
  lottie: ^3.3.0
  http: ^1.2.2
  provider: ^6.1.5+1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.3.2
  google_sign_in: ^6.2.1
  flutter_image_compress: ^2.3.0
  heroicons: ^0.11.0
  connectivity_plus: ^6.0.3
  firebase_remote_config: ^5.1.3
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  firebase_core_web: ^2.24.1
  file_picker: ^10.3.3
  firebase_crashlytics: ^4.3.10
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  rename_app: ^1.3.1
  flutter_test:
    sdk: flutter
  lottie_screen_onboarding_flutter: ^1.1.3
  dot_navigation_bar: ^1.0.2
  floating_frosted_bottom_bar: ^0.0.1
  flutter_font_icons: ^2.2.7
  carousel_slider_plus: ^7.1.1



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "images/splash/ios/Glamify-logo-transparent.png"
  android: true
  ios: true
  web: true

  android_12:
    image: "images/splash/ios/Glamify-logo-transparent.png"
    color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/rsz_1image_2025-08-31_183011488.png"
  min_sdk_android: 21 # optional
  web:
    generate: true
    image_path: "images/rsz_1image_2025-08-31_183011488.png"
    background_color: "#FFFFFF"
    theme_color: "#FF69B4"
  windows:
    generate: true
    image_path: "images/rsz_1image_2025-08-31_183011488.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/rsz_1image_2025-08-31_183011488.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/android/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
